-- set default_master_connection='MYCONNECTION';

use widget_demo;


drop user `demo1`@`199.99.199.199`;
drop user `demo2`@`199.99.199.199`;
drop user `demo3`@`199.99.199.199`;
create user if not exists `demo4`@`199.99.199.199`  identified by 'e4@ookl9jrdriPerploopo!poo8drk70ioji';
create user if not exists `demo5`@`199.99.199.199`  identified by 'o09uikl9jr@riPerploopoopoo8drk70ioji';

alter table demo_widget_company add column company_state varchar(100) after company_city;
update demo_widget_company set company_state='Zinderland' where company_id=1000;
delete from demo_widgets where widget_type_id=1574;
delete from demo_widgets where widget_type_id=1253;
delete from demo_widgets where widget_type_id=1787;
delete from demo_widgets where widget_type_id=1771;
delete from demo_widgets where widget_type_id=2970;

INSERT INTO `demo_widget_customers` VALUES (4133,'Haily Somoza','9805 Bonetta Road','Romaine','Benmark');
INSERT INTO `demo_widget_customers` VALUES (4134,'Twila Colpack','5734 Geary Blvd','Mitchell','Frobnia');
INSERT INTO `demo_widget_customers` VALUES (4135,'Glynnis Radon','2541 Good Cir.','Tetelillas','Anchuria');
INSERT INTO `demo_widget_customers` VALUES (4136,'Maurise Baldock','9809 Frithsden Ave','Foxley Olney','Kreplakistan');
INSERT INTO `demo_widget_customers` VALUES (4137,'Nan Autaubo','5621 Nguyen Reid Way','Buoyton','Lombuanda');
INSERT INTO `demo_widget_customers` VALUES (4138,'Emmey Custodio','3665 Emelina Murray Hwy','Aguacatal','Tyrgyzstan');
INSERT INTO `demo_widget_customers` VALUES (4139,'Eleanore Spycher','2781 Sweetwisp Hwy','Foxley','Lani Lani');
INSERT INTO `demo_widget_customers` VALUES (4140,'Catharine Coan','674 Endicott Hwy','San Braunton','Kinjanja');
INSERT INTO `demo_widget_customers` VALUES (4141,'Josi Tommasino','6085 Princess Alleyway','Ballyconneely Derby','Gamba');
INSERT INTO `demo_widget_customers` VALUES (4142,'Mallory Conde','3746 Pecs Road','Farmford Bath','Findas');
INSERT INTO `demo_widget_customers` VALUES (4143,'Adel Anania','1140 Danger St.','Passfield Metropolis','Fato');
INSERT INTO `demo_widget_customers` VALUES (4144,'Jaquelyn Bosler','10934 Slag Blvd','Munsley Chard','Azania');
INSERT INTO `demo_widget_customers` VALUES (4145,'Doralin Zalwsky','10885 Parvin Rosales Pl.','Tiltonsville Poole','Markovia');
INSERT INTO `demo_widget_customers` VALUES (4146,'Hyacinthe Suber','2256 Holden Blackburn End','Duckhampton Heights','Baltonia');
INSERT INTO `demo_widget_customers` VALUES (4147,'Laurianne Mapston','2133 Solarride Highway','Farmingford Ware','Autrisindia');
INSERT INTO `demo_widget_customers` VALUES (4148,'Iolande Broccolo','5341 Ravage Chandler Ln','Spithorn','Novistrana');
INSERT INTO `demo_widget_customers` VALUES (4149,'Dona Trell','90 Cole Circle','Nearon Metropolis','Salouf');
INSERT INTO `demo_widget_customers` VALUES (4150,'Nixie Klinkhammer','6073 Conrado Christian Parkway','Lowburn','Taronia');
INSERT INTO `demo_widget_customers` VALUES (4151,'Vonnie Pearce','5614 Mearley Frontage','Winterside','Versovia');
INSERT INTO `demo_widget_customers` VALUES (4152,'Alena Parrillo','3774 Mitra Stanton Blvd','Supbrough Stoke','Yurugli');
INSERT INTO `demo_widget_customers` VALUES (4153,'Krystyna Boeson','7948 Rampage Court','Ajax','Bukistan');
INSERT INTO `demo_widget_customers` VALUES (4154,'Mara Bonde','7272 Kim Byway','Farmford Colne','Opperland');
INSERT INTO `demo_widget_customers` VALUES (4155,'Chlo Coppenger','766 Merlin End','Offley','Zamunda');
INSERT INTO `demo_widget_customers` VALUES (4156,'Corri Rusin','9880 Faulkner Parkway','South Antaldence','Cortuguay');
INSERT INTO `demo_widget_customers` VALUES (4157,'Darla Hammerschmidt','8007 Frithsden Route','Melburgh','Zanarkand');
INSERT INTO `demo_widget_customers` VALUES (4158,'Shelby Harvath','10717 Sparklesprig Lane','Farrahville','Khembalung');
INSERT INTO `demo_widget_customers` VALUES (4159,'Leann Chrzan','7365 Willowspark Ave','Clayborro','Inagua');
INSERT INTO `demo_widget_customers` VALUES (4160,'Cyndi Gannaway','329 Kup Hwy','Fockery','Azania');
INSERT INTO `demo_widget_customers` VALUES (4161,'Lucita Duguette','6387 Cedarwing Alley','Eggham','San Pedro');
INSERT INTO `demo_widget_customers` VALUES (4162,'Lind Levenson','835 Woodmere Hwy','Prohampton Island','Findas');
INSERT INTO `demo_widget_customers` VALUES (4163,'Wrennie Kizer','3883 Hitman St.','Nearon Egton','Cascara');
INSERT INTO `demo_widget_customers` VALUES (4164,'TEirtza Vacanti','10088 Terry Corner','Leesen','Bay View');
INSERT INTO `demo_widget_customers` VALUES (4165,'Emmey Kettle','9517 Masoud St.','Snowspell','Chiroubistan');
INSERT INTO `demo_widget_customers` VALUES (4166,'Christal Semidey','615 Claymere Wolf Ave.','North Fireborough','Drackenberg');
INSERT INTO `demo_widget_customers` VALUES (4167,'Antonietta Tortolano','1313 Jerald Avenue','West Hazardville','Schiermeeuwenoog');
INSERT INTO `demo_widget_customers` VALUES (4168,'Lynette Fickle','1621 Cloister Cir.','Nighgate','Bayview');
INSERT INTO `demo_widget_customers` VALUES (4169,'Maryellen Frietsch','9007 Gentry Boulevard','Picton','Bongo Congo');
INSERT INTO `demo_widget_customers` VALUES (4170,'Tess Holla','10158 Arias Franklin Way','Francisco','Orb Union');
INSERT INTO `demo_widget_customers` VALUES (4171,'Gayel Amigo','4220 Rolando Dr.','Grand Farmingkarta','Karistan');
INSERT INTO `demo_widget_customers` VALUES (4172,'Rosella Geathers','10681 Pinpointer Promenade','Kendal','Groland');
INSERT INTO `demo_widget_customers` VALUES (4173,'Maryellen Norbeck','6141 Jimenez End','Ashern','Laevatia');
INSERT INTO `demo_widget_customers` VALUES (4174,'Lula Falwell','2959 Biwi Cir.','Lexingstead','Lichtenburg');
INSERT INTO `demo_widget_customers` VALUES (4175,'Catlaina Wollan','2981 Adele Mcpherson Corner','Alderrest','Phaic Tan');
INSERT INTO `demo_widget_customers` VALUES (4176,'Marjory Hird','5339 Zinat Promenade','Bridgeview','Lyrobia');
INSERT INTO `demo_widget_customers` VALUES (4177,'Rafa Anda','9510 Crippler End','Julmouth Lewes','Ixania');
INSERT INTO `demo_widget_customers` VALUES (4178,'Ronica Neria','10557 Snowdew Alley','Vauxhall Bridge','Kamaria');
INSERT INTO `demo_widget_customers` VALUES (4179,'Caroline Hinger','6032 Sexy Kaiser Ave','Southingworth','Blefuscu');
INSERT INTO `demo_widget_customers` VALUES (4180,'Lynette Altman','6940 Maria Alley','Bajonal Epsom','Santa Prisca');
INSERT INTO `demo_widget_customers` VALUES (4181,'Gerrie Zampaglione','2453 West Blvd','Tidehead Ince','Gnubia');
INSERT INTO `demo_widget_customers` VALUES (4182,'Haily Scheumann','8688 Howe Blvd','Forgemoor','Bangalla');
INSERT INTO `demo_widget_customers` VALUES (4183,'Mellisa Kraasch','3972 Qughiah Sexton Promenade','Patview','Birdwell Island');
INSERT INTO `demo_widget_customers` VALUES (4184,'Celie Cotto','3471 Henjaw Rd','Uplowman Cove','Romanovia');
INSERT INTO `demo_widget_customers` VALUES (4185,'Darby Ear','377 Ernesto Crescent','Francisco Hedon','Baraza');
INSERT INTO `demo_widget_customers` VALUES (4186,'Shawnee Keese','1228 Oldfield Ave','Helogzhong','Brazuela');
INSERT INTO `demo_widget_customers` VALUES (4187,'Cammie Lindabury','2797 Sechlainn Avenue','Begtuok Town','Kalya');
INSERT INTO `demo_widget_customers` VALUES (4188,'Charisse Amdahl','3277 Paul Blvd','Bellby','Yugopotamia');
INSERT INTO `demo_widget_customers` VALUES (4189,'Averyl Palazzi','2244 Rolando Road','Randridge Village','Yurugli');
INSERT INTO `demo_widget_customers` VALUES (4190,'Michaeline Darjean','9015 Horn End','Chiddingstone Hills','Pfennig Halbpfennig');
INSERT INTO `demo_widget_customers` VALUES (4191,'Tiffany Galapon','149 Rathnat Pl.','Tacupa Brigg','Zoravia');
INSERT INTO `demo_widget_customers` VALUES (4192,'Corri Maus','9017 Rita Way','West Eriskay','Lavernia');
INSERT INTO `demo_widget_customers` VALUES (4193,'Genia Lira','1513 Alma Ave','Cragrest Peel','Ixania');
INSERT INTO `demo_widget_customers` VALUES (4194,'Marylinda Stumpf','3538 DecemberVampyre St.','Snowspell','Katzenstok');
INSERT INTO `demo_widget_customers` VALUES (4195,'Averyl Horelick','8838 Luna Drive','Illmere Bacup','Caspak');
INSERT INTO `demo_widget_customers` VALUES (4196,'Karil Marasigan','2871 Faulkner Park','Fairkarta Deal','Birani');
INSERT INTO `demo_widget_customers` VALUES (4197,'Reine Morrish','6349 Oakring Loop','Veryan','Island of Sodor');
INSERT INTO `demo_widget_customers` VALUES (4198,'Dalia Isip','10513 Port Blvd','East Cumnock Blyth Megacity','New Swissland');
INSERT INTO `demo_widget_customers` VALUES (4199,'Gerrie Eavey','4637 Animal Drive','Rainhill','Elbonia');
INSERT INTO `demo_widget_customers` VALUES (4200,'Anneliese Phare','9148 Richardson Hwy','Misthall','Absurdsvani');
INSERT INTO `demo_widget_customers` VALUES (4201,'Deedee Asaro','3214 Quutwess Knapp Promenade','Yarmouth','Ecuarico');
INSERT INTO `demo_widget_customers` VALUES (4202,'Debora Massimo','7177 Stormy Frontage','Milston Town','Bretonnia');
INSERT INTO `demo_widget_customers` VALUES (4203,'Sande Haymer','311 Casey Ct.','Alvechurch','Gaad');
INSERT INTO `demo_widget_customers` VALUES (4204,'Sephira Olsson','9619 Hazelsquawk Park','Ashridge','North Sarrawak');
INSERT INTO `demo_widget_customers` VALUES (4205,'Norma Rulnick','1999 Rage Transversal','Gale Derby','Zoravia');
INSERT INTO `demo_widget_customers` VALUES (4206,'Jean Colmenero','4799 Heyes Route','Falmouth','Eurasian Dynasty');
INSERT INTO `demo_widget_customers` VALUES (4207,'Marcile Rieves','104 Imogen Road','Serfall','Zakkestan');
INSERT INTO `demo_widget_customers` VALUES (4208,'Catharine Siemer','10604 Lei Pl.','Tay Megacity','Nibia');
INSERT INTO `demo_widget_customers` VALUES (4209,'Eda Stangl','1538 Green Baldwin Blvd','Slyborough','Lillitania');
INSERT INTO `demo_widget_customers` VALUES (4210,'Helga Baratto','8770 Triple Avenue','Albany Colne Municipality','Chekia');
INSERT INTO `demo_widget_customers` VALUES (4211,'Tami Rua','7668 Aedan Ct.','Cumnock Villa','Nea So Copros');
INSERT INTO `demo_widget_customers` VALUES (4212,'Liuka Maslow','7848 Ciar Ct.','Eriskay','Transia');
INSERT INTO `demo_widget_customers` VALUES (4213,'Rose Filthaut','5500 Applegaze Mcgrath Route','Tattershall','Val Verde');
INSERT INTO `demo_widget_customers` VALUES (4214,'Darcee Philavong','2628 Kennedy Place','Falmouth','Vambria');
INSERT INTO `demo_widget_customers` VALUES (4215,'Gayel Ranck','6045 ClintBob Carney Way','Lardtorthorpe','Andalasia');
INSERT INTO `demo_widget_customers` VALUES (4216,'Saidee Boehner','9486 Pace Parkway','Ghosfort','Mordor');
INSERT INTO `demo_widget_customers` VALUES (4217,'Nan Servin','10350 Heyes Ave','Bowthorpe Crook','Land of the Houyhnhnms');
INSERT INTO `demo_widget_customers` VALUES (4218,'Allyn Shertzer','4523 Grip Hoover Frontage','Transham Pond','Patusan');
INSERT INTO `demo_widget_customers` VALUES (4219,'Nixie Lourence','4325 Zuhajah Byway','New Fairkarta','Saradia');
INSERT INTO `demo_widget_customers` VALUES (4220,'Rosanne Neikirk','2713 Henjaw Dr.','Fairkarta','Dawsbergen');
INSERT INTO `demo_widget_customers` VALUES (4221,'Zandra Laitila','5102 Keefe Promenade','Farmingbrough','Bapetikosweti');
INSERT INTO `demo_widget_customers` VALUES (4222,'Christabella Feagen','6627 Cunnery Route','Sagegrad Megacity','Kamanga');
INSERT INTO `demo_widget_customers` VALUES (4223,'Odette Marasigan','10408 Rampage Highway','Frostworth Megacity','Taronia');
INSERT INTO `demo_widget_customers` VALUES (4224,'Fae Stolley','6375 Jibbi Cir.','Southingworth','Bretzelburg');
INSERT INTO `demo_widget_customers` VALUES (4225,'Codee Pachew','3508 Jackson Alley','Biltorsing','Zanzibar Land');
INSERT INTO `demo_widget_customers` VALUES (4226,'Cati Sleger','11120 Macdonald Leblanc Ave.','Antaldence','Hudatvia');
INSERT INTO `demo_widget_customers` VALUES (4227,'Phil Isenbarger','6929 Slater Alleyway','Ashern Falls','Greater Bezerkistan');
INSERT INTO `demo_widget_customers` VALUES (4228,'Uta Pacholec','9689 Blass Mccann Path','Serfall','Aurelia');
INSERT INTO `demo_widget_customers` VALUES (4229,'Merola France','10306 Merith Court','Tibayrell','Strackenz');
INSERT INTO `demo_widget_customers` VALUES (4230,'Carissa Mccalop','8448 Fulgenzio Frontage','Uplowman','Bensalem');
INSERT INTO `demo_widget_customers` VALUES (4231,'Adelice Fondow','10893 Hitman Turner Transversal','Wildecliff','Kurland');
INSERT INTO `demo_widget_customers` VALUES (4232,'Gracie Dolle','7088 Hammond End','Queensburg Frome','Ethniklashistan');
INSERT INTO `demo_widget_customers` VALUES (4233,'Tarrah Squitieri','1244 Gavin Murray End','Shavebury','Kenyopia');
INSERT INTO `demo_widget_customers` VALUES (4234,'Minnnie Ronchetto','2645 Huffman Dr.','Delphine City','Lani Lani');
INSERT INTO `demo_widget_customers` VALUES (4235,'Donelle Ary','6801 Ponce Lane','Roseview Frome','Adjikistan');
INSERT INTO `demo_widget_customers` VALUES (4236,'Tarra Kaluzny','942 Grax Braun Boulevard','Foxhampton Leek','Mandalia');
INSERT INTO `demo_widget_customers` VALUES (4237,'Eleonora Ledlow','4026 Gateacre Mckinney Path','Firemore Ince','Fawzia');
INSERT INTO `demo_widget_customers` VALUES (4238,'Katuscha Nishikawa','680 Glyn Ellison Road','Duckhampton','Cortuguay');
INSERT INTO `demo_widget_customers` VALUES (4239,'Rakel Joecks','4789 Devonshire Dr.','Exeter Ryde','Bahkan');
INSERT INTO `demo_widget_customers` VALUES (4240,'Merrili Profitt','5645 Kim Berger Route','Balones Poole','Axphain');
INSERT INTO `demo_widget_customers` VALUES (4241,'Emmeline Kesten','9183 Horn Byway','Copperborro','Mamaland');
INSERT INTO `demo_widget_customers` VALUES (4242,'Mirabel Shellenberger','5866 Gateacre Ave.','Zapatosa City','Maguadora');
INSERT INTO `demo_widget_customers` VALUES (4243,'Querida Feela','420 Kane Berg Highway','Hardby','Pala');
DELETE from `demo_widget_customers` where customer_id=1050;
DELETE from `demo_widget_customers` where customer_id=1063;
DELETE from `demo_widget_customers` where customer_id=1079;
DELETE from `demo_widget_customers` where customer_id in (1118,1119,1120,1121,1139);

DELIMITER //

CREATE PROCEDURE new_proc ()
 BEGIN
  DECLARE Z integer;
  SET Z=1;
 END;
//

DELIMITER ;
DELIMITER //

CREATE FUNCTION new_func ()
 RETURNS INT
BEGIN
  RETURN 1;
END;
//

DELIMITER ;

INSERT INTO `demo_widgets` VALUES (5497,1182,'unitizer rattlingly','brown','new','Egestas, sapien auctor pretium.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5498,1034,'asclepiadeous','purple','new','Purus. Praesent at just.','Coopers');
INSERT INTO `demo_widgets` VALUES (5499,2918,'thoracoscopy scrimshorn','red','new','Vehicula purus. Praesent.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5500,1263,'stats','matte','poor','Ultricies tellus, sed scelerisque ex.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5501,2715,'distasteful','red','new','Faucibus volutpat sem. Sed dapibus nequ.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5502,2406,'propaedeutical','gold','new','Pretium nunc. Etiam vulputa.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5503,2354,'rerun','brown','scratched','Dapibus neque in est ornare, et.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5504,1828,'virilely','orange','new','Proin ut pharetra tellus, nec dictum.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5505,2789,'preadjunct','gold','new','Eget nisi. Duis pellentesque cons.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5506,2545,'zeks apologizer','chrome','new','Et mattis tellus tincidunt.','Coopers');
INSERT INTO `demo_widgets` VALUES (5507,1449,'spadixes','gold','scratched','Diam tortor, dignissim quis est.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5508,1049,'slatey','brown','scratched','Eu mi. Maecenas sed vehi.','Coopers');
INSERT INTO `demo_widgets` VALUES (5509,2958,'tonsillectome trapped','green','new','Neque in est ornare, et ull.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5510,2109,'thankers unfailableness','brown','new','Arcu ut sapien gravida, et mattis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5511,3119,'guttural','gold','scratched','Tellus enim, interdum non aliquam ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5512,1524,'resink','white','scratched','Et ullamcorper nisl faucibu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5513,1153,'unentrance nondivergent','black','new','Maecenas sed vehicula purus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5514,1420,'antiprohibitionist','brown','damaged','Cursus ut nibh. Vivamus blandit mi dolor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5515,2790,'saratogan','matte','new','Odio quis augue fermentum accumsan.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5516,1501,'monochlor xanthans','white','new','Dolor, at aliquet massa turpis eget.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5517,3048,'stageful','orange','new','Gravida, odio leo hendrerit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5518,1206,'grapnel unfamous','matte','new','Tellus, nec dictum justo. Quisque in ult.','Coopers');
INSERT INTO `demo_widgets` VALUES (5519,1115,'labionasal','chrome','new','Auctor pretium dictum, enim qua.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5520,2344,'tormentful','matte','new','Varius eu malesuada in.','Coopers');
INSERT INTO `demo_widgets` VALUES (5521,1893,'incorporeal','gold','new','Nibh. Vivamus blandit mi dolor.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5522,1895,'vaccinee','purple','new','Malesuada augue. Aliquam.','Coopers');
INSERT INTO `demo_widgets` VALUES (5523,2777,'hemoproctia','black','poor','In, fringilla pretium nunc. Etiam vulp.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5524,2269,'saccobranchiata','white','new','Mi dolor, sit amet hendrerit.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5525,1798,'circumnutate','purple','new','Donec egestas, sapien auctor.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5526,2705,'freezer','green','new','Neque, tempor quis lacus eget, faucibus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5527,1124,'unakites','matte','new','Faucibus mollis dolor augue vel orci.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5528,1963,'acrydium subarmor','orange','new','Aliquam ut, cursus ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5529,3037,'castigate','gold','new','Purus tincidunt sagittis. Proin.','Coopers');
INSERT INTO `demo_widgets` VALUES (5530,1194,'twangers','matte','new','Mi dolor, sit amet.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5531,1164,'unstuffy','matte','new','Nec dictum justo. Quisque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5532,3121,'vivaces','gold','new','Dolor augue vel orci. Nulla tellus enim.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5533,1888,'tokamaks','chrome','new','Nec dictum justo. Quisque in ultricies tel.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5534,2862,'ylems','white','new','Quis lacus eget, faucib.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5535,1163,'lemography','orange','new','Mi. Maecenas sed vehicula puru.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5536,3000,'foliature','red','new','Ut, cursus ut nibh. Viva.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5537,2210,'sillibub','white','new','Eget, faucibus volutpat sem.','Coopers');
INSERT INTO `demo_widgets` VALUES (5538,2202,'foliature','purple','new','Quisque in quam et tellus facilisis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5539,1797,'wonk','chrome','new','Vel orci. Nulla tellus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5540,1956,'urethrorrhea','matte','new','Pretium dictum, enim quam hendrer.','Coopers');
INSERT INTO `demo_widgets` VALUES (5541,2667,'stith','purple','new','Enim quam hendrerit sem.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5542,1429,'weepie','brown','new','Malesuada in, fringilla pretiu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5543,1488,'kilocycle','blue','poor','Tellus, sed scelerisque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5544,1133,'yocked','black','new','Cursus ut nibh. Vivamus blandit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5545,2816,'vetivert','orange','new','Sit amet hendrerit purus tincidunt sagi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5546,2172,'blameless osteoid','purple','new','Purus tincidunt sagittis. Proin ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5547,1085,'trug','black','poor','Et mattis tellus tincidunt. Integer sed qua.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5548,1731,'vaudois','chrome','new','Hendrerit dolor, at aliquet.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5549,1019,'biblicism','blue','damaged','Aliquam ut, cursus ut nibh. Vivam.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5550,1914,'sidebars','black','damaged','Ut nibh. Vivamus blandit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5551,2254,'epitenon','chrome','new','Vulputate arcu ut sapien gravida, et.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5552,1522,'zazens','matte','new','Scelerisque ex. Aenean.','Coopers');
INSERT INTO `demo_widgets` VALUES (5553,1648,'schistaceous','chrome','new','Etiam vulputate arcu ut sapien gravida.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5554,1917,'subnet','red','damaged','Sem neque, tempor quis lacus eget.','Coopers');
INSERT INTO `demo_widgets` VALUES (5555,2729,'fermerer','chrome','new','Quam est. Sed sem neque, tempor quis lacus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5556,1028,'displeasedly','orange','poor','Ut molestie gravida, odio.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5557,1177,'dilatingly','white','poor','Eget nisi. Duis pellentesque con.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5558,1636,'subproduct','red','new','Malesuada augue. Aliquam vel.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5559,1344,'wrassled','blue','poor','Malesuada in, fringilla pretium.','Coopers');
INSERT INTO `demo_widgets` VALUES (5560,2142,'physonectae','matte','new','Enim, interdum non aliquam ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5561,1290,'subgoal','green','new','Pellentesque lacinia semper odio.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5562,2243,'unbouncy','white','new','In, fringilla pretium nunc. Etia.','Coopers');
INSERT INTO `demo_widgets` VALUES (5563,1809,'confederationist','orange','damaged','Vehicula purus. Praesent at.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5564,2452,'spookery','purple','new','Faucibus. Fusce facilisis, eros ut.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5565,2764,'vanned subnets','black','new','Augue. Aliquam vel odio qui.','Coopers');
INSERT INTO `demo_widgets` VALUES (5566,1148,'yatters','gold','damaged','Sed dapibus neque in est.','Coopers');
INSERT INTO `demo_widgets` VALUES (5567,2782,'predisposedly','matte','new','Nullam nulla arcu, varius eu malesuada in.','Coopers');
INSERT INTO `demo_widgets` VALUES (5568,2774,'subpanel','black','new','Neque, tempor quis lacus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5569,2342,'recept','brown','scratched','Purus tincidunt sagittis. Proi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5570,2763,'microdrawing','blue','damaged','Quisque in quam et tellus facili.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5571,2434,'zymosan','blue','damaged','Pretium dictum, enim quam hen.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5572,1906,'inconvertibility','chrome','new','Nibh. Vivamus blandit mi dolor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5573,1535,'outferret','orange','new','Eget nisi. Duis pellentesque cons.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5574,1727,'phalarism titfer','blue','new','Enim quam hendrerit sem, faucibus mollis.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5575,1563,'pointer','red','new','Ex. Aenean diam tortor, dignissim quis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5576,1664,'sleepify','orange','damaged','Arcu, varius eu malesu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5577,2763,'umiaqs','brown','new','Etiam vulputate arcu ut sapien gravida.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5578,1197,'spoofery','red','new','At justo orci. Pellentesque lacinia semper.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5579,2826,'natricine','red','new','Ut pharetra tellus, nec.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5580,2947,'spackles telestic','chrome','new','At justo orci. Pellentesque lac.','Coopers');
INSERT INTO `demo_widgets` VALUES (5581,1300,'silk tamari','chrome','scratched','Purus. Praesent at justo.','Coopers');
INSERT INTO `demo_widgets` VALUES (5582,3159,'twibil tanyoan','chrome','new','Pharetra tellus, nec dictum justo.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5583,1809,'indignance','purple','new','Arcu ut sapien gravida, et mat.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5584,3182,'wiseass','black','new','Diam tortor, dignissim qui.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5585,1113,'surflike imminution','brown','scratched','Sem neque, tempor quis lacu.','Coopers');
INSERT INTO `demo_widgets` VALUES (5586,2879,'slurbow physonectae','purple','new','Nulla tellus enim, interdum non aliquam ut.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5587,1847,'varactor','gold','new','Quis augue fermentum accumsan.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5588,1717,'oxbiter silklike','blue','new','Etiam vulputate arcu ut sapien.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5589,1843,'taillamp','gold','new','Maecenas sed vehicula purus. Praesent at.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5590,2572,'tsorriss','green','damaged','Tellus, sed scelerisque ex.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5591,2910,'ornithon','red','new','Id, vulputate malesuada augue.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5592,1062,'yardworks','white','poor','Sem neque, tempor quis lacus eget, fau.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5593,3181,'macromeric','red','new','Duis pellentesque consec.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5594,1072,'sleaze','orange','new','Malesuada augue. Aliqu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5595,2207,'lampers','black','scratched','Dolor, at aliquet massa turpis.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5596,1326,'misliken','red','new','Ex. Aenean diam tortor, digniss.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5597,1068,'mandelic','purple','new','Purus tincidunt sagitti.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5598,1788,'outweary','gold','new','Aliquet massa turpis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5599,2096,'kilocycle zaddick','brown','new','Duis pellentesque consectetur.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5600,3070,'bipyridyl','blue','new','Sapien gravida, et mattis tellus tincidunt.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5601,2799,'yucks','blue','new','Ut nibh. Vivamus blandit.','Coopers');
INSERT INTO `demo_widgets` VALUES (5602,1254,'ufologies','gold','scratched','Nisi. Duis pellentesque consectetur volu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5603,3009,'withdrawment','purple','scratched','In quam et tellus facilisis fermentum. Mau.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5604,2642,'taramas','orange','new','Aliquet massa turpis eget nisi. Duis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5605,2008,'bridle','orange','new','Turpis eget nisi. Duis pellentesque con.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5606,2830,'xylitol','blue','poor','Neque, tempor quis lacus eget.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5607,3094,'nonimmigrant seedbox','blue','new','Non aliquam ut, cursus ut.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5608,2094,'punnigram','red','new','Et tellus facilisis fermentum. Mauris.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5609,1930,'anesthetist complacent','matte','new','Enim quam hendrerit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5610,2925,'vuggier lampers','matte','scratched','Facilisis, eros ut molestie gravida.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5611,1738,'hoggy','orange','damaged','Ullamcorper nisl faucibus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5612,2608,'trapped','purple','new','In ultricies tellus, sed scele.','Coopers');
INSERT INTO `demo_widgets` VALUES (5613,1575,'tamari','chrome','poor','Faucibus mollis dolor augu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5614,2155,'glossarize','blue','damaged','Enim quam hendrerit sem, faucibus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5615,2881,'sussed','green','scratched','Ut molestie gravida, odio leo hendr.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5616,1870,'sparrer','red','new','At justo orci. Pellentesque lacinia semp.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5617,3057,'evincement','white','new','Eu mi. Maecenas sed vehicula purus. Praesen.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5618,1390,'twanger','brown','new','Faucibus mollis dolor augue vel.','Coopers');
INSERT INTO `demo_widgets` VALUES (5619,2275,'untwisted','purple','new','Odio quis augue fermentum.','Coopers');
INSERT INTO `demo_widgets` VALUES (5620,1146,'zeroth tatars','red','new','Tortor, dignissim quis est id, vulputa.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5621,1205,'superspy','purple','new','Sed eu mi. Maecenas sed vehicula.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5622,3098,'epigenetic','matte','new','Sem neque, tempor quis lacus eget, fauci.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5623,2171,'vacs','orange','new','Dictum, enim quam hendrerit sem.','Coopers');
INSERT INTO `demo_widgets` VALUES (5624,2870,'ylem','black','poor','Orci. Pellentesque lacinia semper odio.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5625,2588,'testates','purple','new','Vulputate arcu ut sap.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5626,2629,'hedgy nirles','blue','poor','Fringilla pretium nunc.','Coopers');
INSERT INTO `demo_widgets` VALUES (5627,2630,'tylosin','black','new','Quam est. Sed sem neque, tempor qui.','Coopers');
INSERT INTO `demo_widgets` VALUES (5628,1175,'rollick unpunishable','brown','damaged','Arcu ut sapien gravida.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5629,1373,'tranche','gold','new','In ultricies tellus, sed scelerisque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5630,1224,'spritz','matte','damaged','Ut nibh. Vivamus blandit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5631,2951,'stomachlessness','orange','poor','Orci. Pellentesque.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5632,2470,'heterochronic','purple','new','Augue. Aliquam vel odio quis augue.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5633,2446,'typesetting telson','gold','new','Dolor, at aliquet massa turpis eget nisi.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5634,3016,'lingenberry','red','new','Facilisis, eros ut molestie gravida.','Coopers');
INSERT INTO `demo_widgets` VALUES (5635,1340,'anaglyph','red','new','Integer sed quam est. Sed.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5636,3130,'nonfermentative','blue','poor','Arcu, varius eu malesuada in.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5637,3107,'sisseton','white','poor','Purus tincidunt sagittis. Proi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5638,2366,'somniloquy','black','new','Ex. Aenean diam tortor, dignissim quis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5639,1324,'zloties','orange','new','Ornare, et ullamcorper nisl faucibus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5640,2220,'decohesion','blue','scratched','Dictum justo. Quisque in ultricies tellus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5641,1394,'apportionable','matte','new','Hendrerit dolor, at aliquet massa.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5642,2020,'vegie','gold','damaged','Dictum, enim quam hendre.','Coopers');
INSERT INTO `demo_widgets` VALUES (5643,2011,'tellys','green','new','Nec dictum justo. Quisque in ultricies.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5644,1965,'subscale','gold','new','Eros ut molestie gravida, odio leo hendreri.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5645,3188,'disbelief','chrome','poor','Tempor quis lacus eget, fauc.','Coopers');
INSERT INTO `demo_widgets` VALUES (5646,1582,'welly treen','purple','new','Tellus tincidunt. Integer sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5647,1682,'zazens','gold','new','Sem neque, tempor quis lacus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5648,1905,'spiff','matte','new','Donec egestas, sapien.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5649,2967,'wellie hounding','chrome','poor','At justo orci. Pellentesque lacinia sem.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5650,2416,'methought','purple','new','Et tellus facilisis.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5651,1810,'garawi skywalks','gold','poor','Sagittis. Proin ut pharetr.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5652,2885,'physonectae','gold','damaged','In est ornare, et ullamco.','Coopers');
INSERT INTO `demo_widgets` VALUES (5653,2103,'beguilement synth','chrome','new','Sed eu mi. Maecenas.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5654,2983,'dicatalexis','red','new','Quam hendrerit sem, fau.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5655,1362,'unbusted','purple','new','Turpis eget nisi. Duis pellentesqu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5656,1279,'sigillarian tonguiness','red','new','Mollis dolor augue vel orci.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5657,2940,'yquem','red','new','Mollis dolor augue vel orci.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5658,1813,'dephlegmator','matte','new','Diam tortor, dignissim quis est.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5659,1438,'introductoriness','green','new','Ut, cursus ut nibh. Vivamus blandit.','Coopers');
INSERT INTO `demo_widgets` VALUES (5660,3181,'grama','black','new','Dapibus neque in est.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5661,1291,'hecte','white','new','Fringilla pretium nunc.','Coopers');
INSERT INTO `demo_widgets` VALUES (5662,2040,'subzero','orange','new','Sed scelerisque ex. Aenean diam.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5663,1317,'phrygium','purple','damaged','Enim, interdum non aliqu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5664,3041,'blameless','white','new','Dapibus neque in est.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5665,2414,'vanitory','matte','scratched','Consectetur volutpat. Donec.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5666,2275,'warison ultrahot','chrome','new','Eget, faucibus volutpat sem. Sed dapibu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5667,2262,'collaborationism polarography','orange','new','Amet hendrerit purus tincid.','Coopers');
INSERT INTO `demo_widgets` VALUES (5668,2957,'signees','black','scratched','Sapien auctor pretium dictum.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5669,1065,'spoofer','gold','new','Est ornare, et ullamcorper nisl.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5670,2362,'glottiscope','chrome','new','Eget, faucibus volutpat.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5671,2836,'uranias vitrain','black','new','Tellus, sed scelerisque ex. Aenea.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5672,1471,'tenorist','red','new','Sed quam est. Sed sem neque, tempo.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5673,1914,'middlings','matte','new','Justo orci. Pellentesque lacinia semper.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5674,2111,'titfer','green','new','Fermentum accumsan sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5675,2704,'eellike','white','new','Molestie gravida, odio leo hendrerit dolor.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5676,2106,'zill','blue','new','Enim quam hendrerit.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5677,2725,'somal','chrome','scratched','Dolor, sit amet hendr.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5678,1884,'mandelic','matte','new','Est ornare, et ullamcorper nisl.','Coopers');
INSERT INTO `demo_widgets` VALUES (5679,2790,'sifaka pharyngotonsillitis','orange','new','Nec dictum justo. Quisque in ultricies.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5680,2518,'thymosin','green','new','Est. Sed sem neque, tempor quis lacus ege.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5681,1551,'superhit','blue','new','Vivamus blandit mi dolor, sit amet hendre.','Coopers');
INSERT INTO `demo_widgets` VALUES (5682,1606,'solitons','white','new','Id, vulputate malesuada augue. Aliquam.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5683,1129,'menorrhagia','green','new','Tincidunt. Integer sed quam est. Sed sem.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5684,3109,'terminable','gold','new','Egestas, sapien auctor pretiu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5685,1270,'nonsparking','red','new','Nulla arcu, varius eu males.','Coopers');
INSERT INTO `demo_widgets` VALUES (5686,2436,'whamo','matte','new','Dictum justo. Quisque in ultricies.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5687,2934,'onagraceous','gold','new','Quam et tellus facilisis fermentum.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5688,1914,'preofficially','matte','poor','Accumsan sed eu mi. Maecenas sed vehicu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5689,1980,'confederationist','white','new','Mollis dolor augue vel.','Coopers');
INSERT INTO `demo_widgets` VALUES (5690,2352,'pyrocellulose','white','new','Justo orci. Pellentesque lacinia sempe.','Coopers');
INSERT INTO `demo_widgets` VALUES (5691,1736,'ornithon','red','new','Ut sapien gravida, et mattis tellus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5692,2904,'presumptuous','black','new','Odio leo hendrerit dolor, at aliquet mas.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5693,3020,'invective','white','damaged','Amet hendrerit purus tincidunt sagitti.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5694,3100,'worriedness caesardom','red','new','Nisi. Duis pellentesque.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5695,1091,'solei','matte','new','Eros ut molestie gravida, odio leo hendreri.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5696,2130,'aischrolatreia','orange','new','Purus tincidunt sagittis. Proi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5697,3062,'vouvary','black','new','Sed vehicula purus. Praesent at jus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5698,2733,'brotulid','brown','new','Quam est. Sed sem neque.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5699,1147,'unbanned','chrome','new','Nulla arcu, varius eu males.','Coopers');
INSERT INTO `demo_widgets` VALUES (5700,2369,'umangites','black','scratched','Quis augue fermentum accumsan.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5701,1820,'stolport','black','scratched','Vivamus blandit mi dolor, sit.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5702,2808,'toolmark','chrome','scratched','Dolor, sit amet hendrerit.','Coopers');
INSERT INTO `demo_widgets` VALUES (5703,1728,'ultrahot thinners','matte','new','Sem, faucibus mollis dolor augue vel.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5704,2183,'shamefacedly','white','new','Est ornare, et ullamcorper nisl.','Coopers');
INSERT INTO `demo_widgets` VALUES (5705,1184,'inaxon','brown','damaged','Enim quam hendrerit sem, faucibus moll.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5706,2089,'heterochronic','blue','scratched','Mi. Maecenas sed vehicula purus. Praesent.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5707,2957,'wackos castigate','blue','new','Et tellus facilisis fermentu.','Coopers');
INSERT INTO `demo_widgets` VALUES (5708,1799,'subgums unmackly','matte','new','Arcu, varius eu malesuada in, fringilla.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5709,2730,'monk','purple','new','Neque, tempor quis lacus eget.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5710,1357,'antimycotic','blue','new','Dolor augue vel orci. Nulla tellus enim.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5711,2657,'houselet preimpress','white','new','Augue fermentum accumsan sed.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5712,2849,'tailfans','matte','new','Facilisis fermentum. Maur.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5713,1499,'uncompassionate','brown','scratched','Non aliquam ut, cursus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5714,2598,'unimpenetrable tokamaks','matte','new','Fermentum. Mauris sit amet.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5715,1662,'woopsed unsteck','matte','new','In, fringilla pretium nunc. Etiam.','Coopers');
INSERT INTO `demo_widgets` VALUES (5716,2532,'elaps','brown','new','Mi dolor, sit amet hendrerit purus tincid.','Coopers');
INSERT INTO `demo_widgets` VALUES (5717,1457,'heterolysis','white','scratched','Mi dolor, sit amet hendrer.','Coopers');
INSERT INTO `demo_widgets` VALUES (5718,1872,'ateleological','gold','new','Odio leo hendrerit dolor, at aliquet mass.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5719,1183,'sublunar','red','damaged','Pellentesque consectetur volutpat.','Coopers');
INSERT INTO `demo_widgets` VALUES (5720,1938,'repudiationist specced','black','poor','Semper odio. Quisque in quam et tellus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5721,2718,'xi','gold','new','Eros ut molestie gravida, odio leo.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5722,1154,'basos','red','new','Sed eu mi. Maecenas sed vehicula.','Coopers');
INSERT INTO `demo_widgets` VALUES (5723,2148,'ayelp','blue','new','Dapibus neque in est ornare, et.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5724,2237,'toying viga','matte','new','Proin ut pharetra tellus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5725,2086,'faineance','blue','damaged','Quam hendrerit sem, faucibus molli.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5726,2637,'disbelief','purple','new','Integer sed quam est. Sed sem neque.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5727,2259,'sublots','chrome','new','Mattis tellus tincidunt. Integer sed.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5728,1472,'erinaceous','blue','new','Varius eu malesuada in, fringilla pretium.','Coopers');
INSERT INTO `demo_widgets` VALUES (5729,1371,'undotted','chrome','new','Quis augue fermentum accumsan sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5730,1022,'tushie','blue','new','Ut, cursus ut nibh. Vivamus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5731,1687,'unfructuously','chrome','damaged','Enim, interdum non aliquam ut, cursus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5732,1706,'uncuffed','black','poor','Sem neque, tempor quis lacus eget, fau.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5733,1301,'whoofing','gold','new','Vel orci. Nulla tellus enim, interdum non.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5734,1017,'subline fusible','orange','new','Aenean diam tortor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5735,2055,'lovelorn','brown','new','Augue vel orci. Nulla tellus enim, inter.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5736,2004,'octogynia','blue','new','Vehicula purus. Praesent at justo.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5737,1136,'meethelp','blue','new','Volutpat sem. Sed dap.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5738,1571,'squawk','brown','new','Et tellus facilisis fermentum. Maur.','Coopers');
INSERT INTO `demo_widgets` VALUES (5739,3090,'enthusiastical','matte','new','Ut nibh. Vivamus blandit mi dolor, sit.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5740,2883,'unrefusingly','blue','poor','Sed quam est. Sed sem neque, temp.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5741,2263,'zill','red','new','Leo hendrerit dolor, at aliquet mass.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5742,2516,'silk','black','new','Tincidunt sagittis. Proin.','Coopers');
INSERT INTO `demo_widgets` VALUES (5743,2496,'yattering tokomak','black','new','Tellus, nec dictum justo. Quisque in ult.','Coopers');
INSERT INTO `demo_widgets` VALUES (5744,1123,'macromeric','red','scratched','Orci. Nulla tellus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5745,2019,'ganglioid','red','new','Ullamcorper nisl faucibus. Fusce fac.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5746,2962,'tallitim','black','new','Non aliquam ut, cursus ut.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5747,2053,'tranche','green','scratched','Non aliquam ut, cursus ut nibh.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5748,2988,'freezer','black','new','Mi dolor, sit amet hendrerit.','Coopers');
INSERT INTO `demo_widgets` VALUES (5749,1158,'hexahydroxy softish','matte','new','Vulputate malesuada augu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5750,1684,'unfrightened','chrome','scratched','Ullamcorper nisl faucibus. Fusce facilis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5751,1467,'untrendy','red','new','Sed dapibus neque in est ornare, et.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5752,2782,'sulu','orange','new','Eros ut molestie gravida, odi.','Coopers');
INSERT INTO `demo_widgets` VALUES (5753,2152,'themed squooshy','purple','new','Ultricies tellus, sed scelerisque ex. Aene.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5754,2012,'nora','matte','new','Quam et tellus facilisis fermentum. Mau.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5755,1914,'zaddick','green','new','Sed sem neque, tempor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5756,2754,'unimpenetrable','orange','new','Leo hendrerit dolor, at aliquet.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5757,1368,'phalarism','blue','scratched','Gravida, et mattis tell.','Coopers');
INSERT INTO `demo_widgets` VALUES (5758,1147,'viroids','green','new','Aenean diam tortor, dignissim.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5759,1434,'amygdalase','white','new','Sem neque, tempor quis lacus eget.','Coopers');
INSERT INTO `demo_widgets` VALUES (5760,2109,'spotlit','gold','new','Massa turpis eget nisi. Duis pellentes.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5761,1823,'nonprobable','blue','new','Sit amet hendrerit purus tinci.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5762,1086,'meteorogram','orange','new','Tellus enim, interdum non.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5763,2958,'caravan pentapolis','orange','damaged','Orci. Pellentesque lacinia.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5764,1461,'sushis','gold','new','Tincidunt. Integer sed.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5765,1841,'spirier','purple','new','Neque, tempor quis lacus eget, faucib.','Coopers');
INSERT INTO `demo_widgets` VALUES (5766,2244,'unkinked','green','new','Nunc. Etiam vulputate arcu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5767,3032,'propagation','orange','new','Hendrerit sem, faucibus molli.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5768,1675,'unjagged','red','new','Dolor, at aliquet massa turpis eget nisi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5769,1166,'firetop','purple','damaged','Proin ut pharetra tellus, nec dict.','Coopers');
INSERT INTO `demo_widgets` VALUES (5770,1168,'nystagmus','chrome','scratched','Justo orci. Pellentesque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5771,1951,'platybrachycephalous','black','new','In est ornare, et ullamcorper nisl fauci.','Coopers');
INSERT INTO `demo_widgets` VALUES (5772,3036,'winless klanswoman','gold','new','Aenean diam tortor, dignissim quis est id.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5773,1505,'yocked','chrome','new','Tellus, sed scelerisque ex. Aen.','Coopers');
INSERT INTO `demo_widgets` VALUES (5774,1648,'quadrumane','green','scratched','Odio. Quisque in quam et tellus facili.','Coopers');
INSERT INTO `demo_widgets` VALUES (5775,3190,'whackos','chrome','new','Dictum justo. Quisque in ultric.','Coopers');
INSERT INTO `demo_widgets` VALUES (5776,2697,'sidebar','matte','new','Dapibus neque in est ornare.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5777,2000,'scunner speedos','green','damaged','Sagittis. Proin ut phare.','Coopers');
INSERT INTO `demo_widgets` VALUES (5778,2269,'wimp recce','purple','new','Orci. Nulla tellus enim, interdum.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5779,1548,'atrocity','red','new','At justo orci. Pellentesque.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5780,2436,'spritzer','brown','new','Sem. Sed dapibus neque in est.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5781,1485,'subtests','green','new','Sagittis. Proin ut pharetra tellus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5782,2073,'obtect','orange','damaged','Auctor pretium dictum, enim quam hendrerit.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5783,2482,'unbeing transversomedial','blue','new','Tellus facilisis fermen.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5784,2925,'antivaccinist','white','new','Molestie gravida, odio leo hendrerit dolor.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5785,1419,'airmark','white','new','Faucibus volutpat sem. Sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5786,2653,'celery','purple','poor','Molestie gravida, odio leo hendre.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5787,1063,'tostadas','chrome','scratched','Sed quam est. Sed sem neque, tempor quis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5788,2356,'foremasthand','purple','new','Vehicula purus. Praesent.','Coopers');
INSERT INTO `demo_widgets` VALUES (5789,1465,'tuxedoed','blue','new','Sed quam est. Sed sem neque, tempo.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5790,2817,'topsider','brown','new','Tellus, nec dictum justo.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5791,1046,'tribase','black','new','Maecenas sed vehicula purus. Praesent at.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5792,2352,'torot','matte','scratched','Nisi. Duis pellentesque consec.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5793,1068,'urania','matte','new','Fermentum accumsan sed eu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5794,1357,'attainability recreative','gold','new','Fermentum accumsan sed eu mi. Maecenas.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5795,1477,'cancroid ruck','gold','new','Quam et tellus facilisi.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5796,1625,'unhedged','black','poor','Accumsan sed eu mi.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5797,1120,'garter forthwith','orange','new','Volutpat sem. Sed dapibus.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5798,1337,'beriberic weltings','red','new','Tempor quis lacus eget, faucibu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5799,3002,'startup','red','new','Arcu ut sapien gravida, et mattis tellu.','Coopers');
INSERT INTO `demo_widgets` VALUES (5800,3139,'sidebar','matte','new','Volutpat sem. Sed dapibu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5801,2999,'goave','purple','damaged','Augue fermentum accumsan sed eu.','Coopers');
INSERT INTO `demo_widgets` VALUES (5802,3057,'unwhite','green','poor','Est id, vulputate malesuad.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5803,2215,'sifaka','black','scratched','Dapibus neque in est ornare.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5804,2738,'tragics','purple','new','Ut pharetra tellus, nec dictu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5805,2791,'presumptuous','red','poor','Dolor, at aliquet massa turpis.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5806,1049,'tubulins','chrome','scratched','In, fringilla pretium nunc.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5807,1042,'unastonished spaetzle','green','new','Accumsan sed eu mi. Maecenas.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5808,1664,'vestigia','purple','new','Hendrerit sem, faucibus mollis dolor augue.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5809,1819,'spaetzle','white','damaged','Mi dolor, sit amet hendrerit purus tin.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5810,2104,'nextly','red','new','Arcu ut sapien gravida, et.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5811,2444,'uropygia','brown','new','Sem, faucibus mollis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5812,1839,'twee','orange','new','Orci. Pellentesque lacinia semper odio.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5813,2026,'spyfault','purple','poor','Odio leo hendrerit dolo.','Coopers');
INSERT INTO `demo_widgets` VALUES (5814,1899,'unfailableness manumission','blue','new','Turpis eget nisi. Duis pellentesque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5815,1648,'zeks','blue','new','Mattis tellus tincidunt. Integer sed quam.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5816,2379,'unbright','purple','new','Etiam vulputate arcu ut sapien gravida.','Coopers');
INSERT INTO `demo_widgets` VALUES (5817,2622,'unbrotherliness','gold','new','Dignissim quis est id, vulputate.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5818,2316,'anthropophagistic','purple','new','Purus tincidunt sagittis. Proin ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5819,1166,'wackos','black','poor','Tincidunt. Integer sed quam est. Sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5820,1633,'wellington','black','scratched','Quisque in ultricies tellus.','Coopers');
INSERT INTO `demo_widgets` VALUES (5821,2502,'sodomize','green','new','Sapien auctor pretium dictum, enim qua.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5822,1032,'sjamboks','brown','new','Quam et tellus facilisis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5823,3140,'apportionable','red','new','Vel odio quis augue fermen.','Coopers');
INSERT INTO `demo_widgets` VALUES (5824,1342,'pointer','orange','damaged','Nisi. Duis pellentesque consec.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5825,1421,'stythe','green','new','In, fringilla pretium nunc. Etiam.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5826,1433,'stopbank','matte','new','Nulla arcu, varius eu malesuada in, fringi.','Coopers');
INSERT INTO `demo_widgets` VALUES (5827,2167,'pobs','gold','scratched','Egestas, sapien auctor pretium dictum.','Coopers');
INSERT INTO `demo_widgets` VALUES (5828,2469,'spirier','green','new','Eu malesuada in, fringilla pret.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5829,2642,'dyophysitism','chrome','new','Et mattis tellus tincidunt.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5830,1553,'spiff proagrarian','orange','new','At justo orci. Pellentesque lacinia.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5831,2694,'archheart','blue','new','Est id, vulputate malesuada.','Coopers');
INSERT INTO `demo_widgets` VALUES (5832,2798,'unkinked','purple','new','Enim quam hendrerit sem, faucib.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5833,1400,'unwist','purple','damaged','Pellentesque consectetur volut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5834,1474,'toker teenybop','matte','new','Enim, interdum non aliquam.','Coopers');
INSERT INTO `demo_widgets` VALUES (5835,1407,'zinger','matte','new','Aenean diam tortor, dignissim qui.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5836,2439,'insulance','black','scratched','Dignissim quis est id, vulput.','Coopers');
INSERT INTO `demo_widgets` VALUES (5837,2788,'unbilled','orange','poor','Facilisis, eros ut molestie gravida, odio.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5838,2678,'sozzled','white','new','Tincidunt sagittis. Proin ut.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5839,1209,'subtrend','green','new','Vulputate arcu ut sapien gravida.','Coopers');
INSERT INTO `demo_widgets` VALUES (5840,2416,'yokozuna','orange','new','Tempor quis lacus eget, fau.','Coopers');
INSERT INTO `demo_widgets` VALUES (5841,2663,'behammer','chrome','new','Integer sed quam est. Sed sem neque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5842,1098,'sillibubs','red','poor','Justo. Quisque in ultricies tellus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5843,1602,'sled','matte','new','Enim quam hendrerit sem, faucibus mollis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5844,1197,'apache','green','new','Lacinia semper odio. Quisque in qua.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5845,1224,'eaglewood','white','new','Cursus ut nibh. Vivamus bland.','Coopers');
INSERT INTO `demo_widgets` VALUES (5846,2914,'lecanium syli','matte','new','At aliquet massa turpis eget nisi.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5847,1610,'blossomtime','green','new','Nulla tellus enim.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5848,1737,'tardyons','chrome','new','Amet hendrerit purus tincidunt.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5849,1320,'unakites','orange','damaged','Sem. Sed dapibus neque in.','Coopers');
INSERT INTO `demo_widgets` VALUES (5850,2331,'snary','blue','new','Odio quis augue fermentum accumsan sed.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5851,3141,'proctoclysis','chrome','poor','Consectetur volutpat. Donec.','Coopers');
INSERT INTO `demo_widgets` VALUES (5852,3164,'sneeshing','purple','new','Etiam vulputate arcu ut.','Coopers');
INSERT INTO `demo_widgets` VALUES (5853,2477,'chaplain','chrome','new','Etiam vulputate arcu ut sap.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5854,1492,'treacliness','blue','new','Lacinia semper odio. Quisque in quam.','Coopers');
INSERT INTO `demo_widgets` VALUES (5855,3136,'unagile','blue','new','Quisque in ultricies tel.','Coopers');
INSERT INTO `demo_widgets` VALUES (5856,2211,'souvlaki stiffed','black','damaged','Sem neque, tempor quis lacu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5857,2014,'displeasedly','gold','new','Id, vulputate malesuada augue.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5858,2269,'yente','white','damaged','Vel orci. Nulla tellus enim, interdum.','Coopers');
INSERT INTO `demo_widgets` VALUES (5859,1249,'individualize osteoid','green','new','Faucibus. Fusce facil.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5860,1881,'snogs','black','new','Eget, faucibus volutpat.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5861,1656,'macromeric','white','damaged','Dolor, at aliquet massa turpis eget nis.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5862,3089,'roominess','chrome','new','Sapien auctor pretium dictum, enim quam.','Coopers');
INSERT INTO `demo_widgets` VALUES (5863,2424,'sigillarian','gold','new','Sapien auctor pretium dictum, enim.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5864,2552,'souvlaki','green','new','Sed scelerisque ex. Aenean diam tort.','Coopers');
INSERT INTO `demo_widgets` VALUES (5865,2149,'unpotted','red','damaged','Fermentum. Mauris sit amet mi turpis. Nun.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5866,2542,'sonobuoy','blue','new','Sed quam est. Sed sem neque, tempor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5867,2888,'apache','brown','scratched','Varius eu malesuada in, frin.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5868,2122,'wauken','gold','new','At justo orci. Pellentesque lacinia semp.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5869,1764,'zaddick imperceptibly','orange','new','Nisl faucibus. Fusce facilisis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5870,2163,'tawdrily','red','new','Purus tincidunt sagittis. Proin ut.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5871,2714,'subzero','matte','new','Vel orci. Nulla tellus eni.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5872,1489,'whinge','purple','scratched','Dolor, sit amet hendr.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5873,1950,'reaccomplish lentibulariaceae','green','new','In quam et tellus fac.','Coopers');
INSERT INTO `demo_widgets` VALUES (5874,2352,'tepals','red','poor','Facilisis, eros ut molestie gravida.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5875,2668,'tinklers','black','new','Varius eu malesuada in, fringilla pre.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5876,2285,'unmeshed','red','new','Faucibus mollis dolor augue.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5877,1669,'hypodorian','green','new','Sapien gravida, et mattis.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5878,2583,'empyrean','black','new','Accumsan sed eu mi. Maecenas sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5879,2802,'pauline','blue','new','Nunc. Etiam vulputate arcu ut sapi.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5880,2783,'microgametocyte','red','new','Neque, tempor quis lacu.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5881,2055,'apinage seedbox','red','damaged','Sem. Sed dapibus neque.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5882,2048,'collaborationism','gold','new','Quisque in quam et tellus facilisis ferm.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5883,1602,'osteoscope brachypyramid','gold','new','Justo orci. Pellentesque lacinia semper.','Coopers');
INSERT INTO `demo_widgets` VALUES (5884,2986,'semiupright','chrome','damaged','Facilisis, eros ut molestie gravida.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5885,1061,'lecanium','green','new','Gravida, et mattis tellus tin.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5886,2098,'genderer','purple','new','Quis est id, vulputate malesuada.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5887,2220,'upbows','matte','new','Praesent at justo orci.','Coopers');
INSERT INTO `demo_widgets` VALUES (5888,1504,'ironback','chrome','new','Augue fermentum accumsan sed.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5889,3140,'ungoverned','gold','new','Praesent at justo orci. Pellentes.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5890,2298,'tavernas','red','new','Neque in est ornare, et ullamcorper nisl.','Coopers');
INSERT INTO `demo_widgets` VALUES (5891,1777,'quadrigamist','black','poor','Ut nibh. Vivamus blandit mi dolor.','Coopers');
INSERT INTO `demo_widgets` VALUES (5892,2492,'upcover','blue','new','Faucibus volutpat sem. Sed dapibus neque.','Coopers');
INSERT INTO `demo_widgets` VALUES (5893,2750,'madelon','red','new','Diam tortor, dignissim quis est id.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5894,1497,'existentially','blue','new','Massa turpis eget nisi. Duis pellen.','Coopers');
INSERT INTO `demo_widgets` VALUES (5895,1549,'subphase','brown','new','Nibh. Vivamus blandit mi dol.','Coopers');
INSERT INTO `demo_widgets` VALUES (5896,1853,'subniche','orange','damaged','Vel orci. Nulla tellus enim.','Coopers');
INSERT INTO `demo_widgets` VALUES (5897,3060,'veejay','chrome','new','Odio quis augue fermentum accu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5898,1659,'unmacho','green','scratched','Nec dictum justo. Quisque in ultri.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5899,1359,'physonectae','black','new','Eget, faucibus volutpat.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5900,2921,'ring','gold','new','Pharetra tellus, nec dictum justo.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5901,2576,'yokozuna soliton','white','new','Sed dapibus neque in.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5902,2917,'vanned','purple','damaged','Vel orci. Nulla tellus enim.','Coopers');
INSERT INTO `demo_widgets` VALUES (5903,1200,'staithes','black','new','Dictum justo. Quisque in ultricies.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5904,1350,'yatter','purple','new','Vehicula purus. Praesent at.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5905,1215,'atheriogaea','black','new','Fusce facilisis, eros.','Coopers');
INSERT INTO `demo_widgets` VALUES (5906,1410,'tushie','purple','scratched','Sed quam est. Sed sem.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5907,1619,'sotted','purple','damaged','Nulla tellus enim, interdum.','Coopers');
INSERT INTO `demo_widgets` VALUES (5908,3175,'counternoise','black','new','Augue. Aliquam vel odio quis augue fermentu.','Coopers');
INSERT INTO `demo_widgets` VALUES (5909,2751,'ulus','brown','new','Est ornare, et ullamcorper nisl.','Coopers');
INSERT INTO `demo_widgets` VALUES (5910,1610,'burnt','white','new','Vivamus blandit mi dolor, sit amet hendrer.','Coopers');
INSERT INTO `demo_widgets` VALUES (5911,3020,'wiggier honduran','brown','scratched','Facilisis fermentum.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5912,2344,'vitrains','blue','scratched','Tellus, nec dictum justo.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5913,3177,'zaddick','orange','new','Sapien auctor pretium dict.','Coopers');
INSERT INTO `demo_widgets` VALUES (5914,3142,'sodom','gold','damaged','Pharetra tellus, nec dictum.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5915,1961,'duroquinone','white','scratched','In, fringilla pretium.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5916,2209,'natricine lionet','gold','new','Quis lacus eget, faucibu.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5917,2181,'whincow','chrome','new','Diam tortor, dignissim.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5918,1090,'pentelic','matte','scratched','Et mattis tellus tincidunt. Inte.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5919,1678,'stuntmen siccity','brown','new','Etiam vulputate arcu ut.','Coopers');
INSERT INTO `demo_widgets` VALUES (5920,1819,'flyless dredge','purple','poor','Consectetur volutpat. Donec.','Coopers');
INSERT INTO `demo_widgets` VALUES (5921,2803,'twinjets','blue','new','Aliquet massa turpis ege.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5922,2947,'eumenes','blue','new','In ultricies tellus, sed.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5923,2202,'tombola twinset','purple','new','Hendrerit purus tincidunt sagittis. Proin.','Coopers');
INSERT INTO `demo_widgets` VALUES (5924,2163,'lin unshowy','matte','new','Faucibus volutpat sem. Sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5925,1365,'spackled','white','new','Quisque in quam et tellus facilisis.','Coopers');
INSERT INTO `demo_widgets` VALUES (5926,3022,'subzero','gold','poor','Et ullamcorper nisl fau.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5927,2262,'unitard','red','new','Vel odio quis augue fermentum accumsan sed.','Coopers');
INSERT INTO `demo_widgets` VALUES (5928,2542,'pointingly psychographic','gold','new','Mattis tellus tincidun.','Coopers');
INSERT INTO `demo_widgets` VALUES (5929,2446,'speedos','green','new','Cursus ut nibh. Vivamus.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5930,2617,'snelled','green','damaged','Ut nibh. Vivamus blandit.','HeadQ');
INSERT INTO `demo_widgets` VALUES (5931,1370,'uncoded','orange','new','Vulputate malesuada augue. Aliquam vel.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5932,2130,'mogilalism','orange','new','Auctor pretium dictum, enim quam hendrerit.','Coopers');
INSERT INTO `demo_widgets` VALUES (5933,2002,'hendecoic','brown','new','Massa turpis eget nisi. Duis pel.','Blacksmith WH');
INSERT INTO `demo_widgets` VALUES (5934,1825,'wireless','purple','new','Semper odio. Quisque.','Coopers');
INSERT INTO `demo_widgets` VALUES (5935,1409,'dephlegmator','chrome','new','Auctor pretium dictum, enim quam hendreri.','Coopers');
INSERT INTO `demo_widgets` VALUES (5936,1226,'babblishly','white','new','Vehicula purus. Praesent at justo orci.','HeadQ');



set global gtid_strict_mode=ON;
/* MASTER_USE_GTID = currentpos is more sensitive to failure */
STOP SLAVE; CHANGE MASTER TO MASTER_USE_GTID = current_pos; START SLAVE;

